# Generated by Django 4.2 on 2023-12-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lodges_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodges',
            name='price',
            field=models.DecimalField(decimal_places=0, default='0.00', max_digits=99999999999999),
        ),
    ]
