# Generated by Django 4.2 on 2023-12-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lodges_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodges',
            name='title',
            field=models.CharField(default='Name of lodge', max_length=100),
        ),
    ]
