# Generated by Django 4.2 on 2023-12-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lodges_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodges',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
    ]
