# Generated by Django 4.2 on 2023-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lodges_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodges',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lodges',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
