# Generated by Django 4.2 on 2023-12-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_lodges_latitude_remove_lodges_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='product.jpg', upload_to='product-images')),
            ],
            options={
                'verbose_name_plural': 'Product Image Gallery',
            },
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Lodge Images'},
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='images',
        ),
        migrations.AddField(
            model_name='productimages',
            name='images',
            field=models.ManyToManyField(related_name='product_images', to='core.productimagegallery'),
        ),
    ]
